-- MySQL Script generated by MySQL Workbench
-- Fri Jul  6 14:18:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cooking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cooking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cooking` DEFAULT CHARACTER SET utf8 ;
USE `cooking` ;

-- -----------------------------------------------------
-- Table `cooking`.`sastojci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooking`.`sastojci` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv_sastojka` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cooking`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooking`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(30) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cooking`.`recepti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooking`.`recepti` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(30) NOT NULL,
  `opis` VARCHAR(30) NOT NULL,
  `kratak_naziv` VARCHAR(30) NOT NULL,
  `naziv_slike` VARCHAR(30) NOT NULL,
  `id_users` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_users` (`id_users` ASC),
  CONSTRAINT `recepti_ibfk_1`
    FOREIGN KEY (`id_users`)
    REFERENCES `cooking`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cooking`.`koliko`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cooking`.`koliko` (
  `id_sastojci` INT(11) NOT NULL,
  `id_recepti` INT(11) NOT NULL,
  `kolicina` INT(11) NOT NULL,
  PRIMARY KEY (`id_sastojci`, `id_recepti`),
  INDEX `id_recepti` (`id_recepti` ASC),
  CONSTRAINT `koliko_ibfk_1`
    FOREIGN KEY (`id_sastojci`)
    REFERENCES `cooking`.`sastojci` (`id`),
  CONSTRAINT `koliko_ibfk_2`
    FOREIGN KEY (`id_recepti`)
    REFERENCES `cooking`.`recepti` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
